#!/usr/bin/env python3

import sys
import rospy
import roslaunch
import os
import rospkg

from simulation_nodes import launch_clover_simulation


if "-h" in sys.argv:
    print("""
    launch_clover_simulation

    DESCRIPTION

        program for debugging clover simulation environment on a bare world

    USAGE

        launch_clover_simulation <path-to-gazebo-world>
    """)

gui = False
if "--gui=true" in sys.argv:
    gui = True

rospy.init_node("launch_clover_simulation")

launch_clover_simulation(sys.argv[1], gui=gui)
rospy.spin()
