#!/usr/bin/env python3

import os
import rospkg
import signal
import subprocess
import sys

rospack = rospkg.RosPack()
pcg_path = rospack.get_path("pcg")
# move to pcg package directory
os.chdir(pcg_path)
args = ["sh", "./scripts/generate.py.sh", *sys.argv[1:]]
process = subprocess.Popen(args)
try:
    process.wait()
    if process.returncode != 0:
        raise Exception("An error occured with running the script.")
except KeyboardInterrupt:
    pass
